/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;
import BBDD.*;
import Clases.*;
import Login.PagPrincipalPsicologo;
import Login.RegistrarsePsicologo;
import Login.RegistrarsePsicologo;
import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alexa
 */
public class Informacion_ingre extends javax.swing.JFrame {
    public static String cedula_pasada_interfaz;
    JFileChooser seleccionar = new JFileChooser();
    byte[] imagen;
    ObjectContainer Base;
    String cod;

    /**
     * Creates new form Informacion
     */
    public Informacion_ingre() {
        initComponents();
         Base = Db4o.openFile("src/BBDD/BaseDat.yap");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_mostrar = new javax.swing.JTable();
        BtnRegresar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txA_text_info = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txt_Titulo = new javax.swing.JTextField();
        btn_ingresar = new javax.swing.JButton();
        imagen_ = new javax.swing.JLabel();
        btn_Ingresar_imagen = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_mostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CODIGO", "TITULO", "TEXTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla_mostrar);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 630, 90));

        BtnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        BtnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        BtnRegresar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        BtnRegresar.setOpaque(false);
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 50, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Informacion");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 151, 37));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Ingresar su informacion:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 220, 10));

        txA_text_info.setColumns(20);
        txA_text_info.setRows(5);
        txA_text_info.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(txA_text_info);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 240, 220));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Ingresar el titulo de la informacion:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        txt_Titulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Titulo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(txt_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 240, 20));

        btn_ingresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ingresar.setText("Ingresar");
        btn_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ingresarMouseClicked(evt);
            }
        });
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 230, -1));

        imagen_.setForeground(new java.awt.Color(204, 204, 204));
        imagen_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen_.setText(" Ingresar Imagen");
        imagen_.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.add(imagen_, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 200, 230));

        btn_Ingresar_imagen.setText("Ingresar Imagen");
        btn_Ingresar_imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ingresar_imagenActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Ingresar_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 220, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 260, 10));

        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 10, 320));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 630, 360));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoClaro.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed

       


    }//GEN-LAST:event_btn_ingresarActionPerformed

  

    public void Ingresa_Info_Publicacion(ObjectContainer Base,String codigoPublic,String codd,String codPsico,Date fecha){
        try {
           Publicacion_Info publi = new Publicacion_Info();
            publi.setCod_Publicacion(codigoPublic);
            publi.setFK_Cod_Informacion(codd);
            publi.setFK_Cod_Psicologo(codPsico);
            publi.setFecha_Publicacion(fecha);
            
            Base.store(publi); 
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error en la publicacion");
        }
         
            
    
    }
    
    
    public void MostrarDatos(ObjectContainer Base) {

        Informacion nacio = new Informacion();
        ObjectSet result = Base.get(nacio);

        DefaultTableModel modelo = (DefaultTableModel) tabla_mostrar.getModel();

        // Limpiar el modelo antes de agregar nuevas filas
        modelo.setRowCount(0);

        while (result.hasNext()) {
            Informacion minaci = (Informacion) result.next();
            modelo.addRow(new Object[]{
                minaci.getCod_Info(),
                minaci.getTitulo_Info(),
                minaci.getTexto_Info(),
                
            });
        }

    }
    
    private void btn_Ingresar_imagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ingresar_imagenActionPerformed
        if (seleccionar.showDialog(null, null) == JFileChooser.APPROVE_OPTION) {
            File archivo = seleccionar.getSelectedFile();
            if (archivo.getName().endsWith("jpg") || archivo.getName().endsWith("jpng") || archivo.getName().endsWith("jpng") || archivo.getName().endsWith("png") || archivo.getName().endsWith("gif")) {
                imagen = AbrirArchivo(archivo); // Store the selected image in the imagen variable
                imagen_.setIcon(new ImageIcon(imagen)); // Update the displayed image on the interface
            } else {
                JOptionPane.showMessageDialog(null, "Archivo no compatible");
            }
        }
    }//GEN-LAST:event_btn_Ingresar_imagenActionPerformed

    private void btn_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresarMouseClicked
       
        
        
         try {
            Informacion info = new Informacion();
            cod = Crear_codigo_info(Base);
            info.setCod_Info(cod);
            
            info.setTitulo_Info(txt_Titulo.getText());
            info.setTexto_Info(txA_text_info.getText());
            info.setImagen(imagen);
            Base.store(info);
            if (RegistrarsePsicologo.cedula_pasada_interfaz==null) {
                javax.swing.JOptionPane.showMessageDialog(this, "La cedula estraida del psicologo esta vacia");
            }
            
            Ingresa_Info_Publicacion(Base, Crear_codigo_public(Base), cod, RegistrarsePsicologo.cedula_pasada_interfaz, new Date());
javax.swing.JOptionPane.showMessageDialog(this, "Se guardo la Informacion");
            
             MostrarDatos(Base);
             Vaciar_datos();
        } catch (Exception e) {
            
        }finally{
        Base.close();
        
        }
        
        
        
        
    }//GEN-LAST:event_btn_ingresarMouseClicked

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        PagPrincipalAdmin prinAdmn = new PagPrincipalAdmin();
        prinAdmn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnRegresarActionPerformed

    public void Vaciar_datos(){
    txt_Titulo.setText("");
    txA_text_info.setText("");
    imagen_.setText("");
    
    }
    
    
    
    public byte[] AbrirArchivo(File archivo) {

        byte[] imagen = new byte[1024 * 683];
        try {
            FileInputStream entrada = new FileInputStream(archivo);
            entrada.read(imagen);
        } catch (IOException e) {
        }
        return imagen;
    }

    public static String Crear_codigo_info(ObjectContainer Base) {

        boolean sall = true;
        int calcular = 0;
        String Codigo;
        do {
            calcular++;

            Codigo = String.format("I%04d", calcular);

            if (Verificar_infor(Base, Codigo) == 0) {
                sall = false;
            }

        } while (sall);

        return Codigo;
    }

    public static String Crear_codigo_public(ObjectContainer Base) {

        boolean sall = true;
        int calcular = 0;
        String Codigo;
        do {
            calcular++;

            Codigo = String.format("PI%04d", calcular);

            if (Verificar_infor_publi(Base, Codigo) == 0) {
                sall = false;
            }

        } while (sall);

        return Codigo;
    }

    public static int Verificar_infor_publi(ObjectContainer Base, String Codigo) {

        Publicacion_Info elInfo = new Publicacion_Info();
        elInfo.setCod_Publicacion(Codigo);
        ObjectSet repuest = Base.get(elInfo);

        return repuest.size();

    }

    public static int Verificar_infor(ObjectContainer Base, String Codigo) {

        Informacion elInfo = new Informacion();
        elInfo.setCod_Info(Codigo);
        ObjectSet repuest = Base.get(elInfo);

        return repuest.size();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacion_ingre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacion_ingre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacion_ingre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacion_ingre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informacion_ingre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JButton btn_Ingresar_imagen;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JLabel imagen_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tabla_mostrar;
    private javax.swing.JTextArea txA_text_info;
    private javax.swing.JTextField txt_Titulo;
    // End of variables declaration//GEN-END:variables
}
