/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Login.RegistrarseGeneral;

/**
 *
 * @author mauca
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        LbTitulo = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BtnCerrarPagina = new javax.swing.JButton();
        BtnIniciarSesion = new javax.swing.JButton();
        BtnRegistrar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbTitulo.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        LbTitulo.setText("Bienvenidos A:");
        PanelPrincipal.add(LbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 330, 50));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ni Uno Mas-Logo-PhotoRoom.png"))); // NOI18N
        PanelPrincipal.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 290, 300));
        PanelPrincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 320, 10));

        BtnCerrarPagina.setBackground(new java.awt.Color(255, 255, 255));
        BtnCerrarPagina.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        BtnCerrarPagina.setText("x");
        BtnCerrarPagina.setToolTipText("Cerrar Pagina dando click aqui");
        BtnCerrarPagina.setBorder(null);
        BtnCerrarPagina.setOpaque(false);
        BtnCerrarPagina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCerrarPaginaMouseClicked(evt);
            }
        });
        BtnCerrarPagina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarPaginaActionPerformed(evt);
            }
        });
        PanelPrincipal.add(BtnCerrarPagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 40, 30));

        BtnIniciarSesion.setBackground(new java.awt.Color(255, 255, 255));
        BtnIniciarSesion.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        BtnIniciarSesion.setText("INICIAR SESIÓN");
        BtnIniciarSesion.setToolTipText("Inicia Sesión Aqui");
        BtnIniciarSesion.setBorder(null);
        BtnIniciarSesion.setOpaque(false);
        BtnIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnIniciarSesionMouseClicked(evt);
            }
        });
        BtnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIniciarSesionActionPerformed(evt);
            }
        });
        PanelPrincipal.add(BtnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 180, 40));

        BtnRegistrar1.setBackground(new java.awt.Color(255, 255, 255));
        BtnRegistrar1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        BtnRegistrar1.setText("REGISTRAR");
        BtnRegistrar1.setToolTipText("Registrate dando click Aqui\n");
        BtnRegistrar1.setBorder(null);
        BtnRegistrar1.setOpaque(false);
        BtnRegistrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRegistrar1MouseClicked(evt);
            }
        });
        BtnRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrar1ActionPerformed(evt);
            }
        });
        PanelPrincipal.add(BtnRegistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 190, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Marco-Imagen.png"))); // NOI18N
        PanelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 760, 480));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoClaro.jpg"))); // NOI18N
        PanelPrincipal.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        getContentPane().add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCerrarPaginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarPaginaActionPerformed
       System.exit(0);
    }//GEN-LAST:event_BtnCerrarPaginaActionPerformed

    private void BtnCerrarPaginaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCerrarPaginaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCerrarPaginaMouseClicked

    private void BtnIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIniciarSesionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnIniciarSesionMouseClicked

    private void BtnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIniciarSesionActionPerformed
        Seleccion selec = new Seleccion();
            selec.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_BtnIniciarSesionActionPerformed

    private void BtnRegistrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegistrar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRegistrar1MouseClicked

    private void BtnRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRegistrar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrarPagina;
    private javax.swing.JButton BtnIniciarSesion;
    private javax.swing.JButton BtnRegistrar1;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel LbTitulo;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
