/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.awt.Color;

/**
 *
 * @author mauca
 */
public class PagCrudJuegosPsicologo extends javax.swing.JFrame {

    /**
     * Creates new form PagCrudJuegosPsicologo
     */
    public PagCrudJuegosPsicologo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        LblInfor2Niño = new javax.swing.JLabel();
        imagen_1_Laberinto = new javax.swing.JLabel();
        btn_Ingresar_imagen1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        btn_Ingresar_imagen2 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        imagen_1_Laberinto1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        LblInfor2Niño1 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        LblInfor2Niño2 = new javax.swing.JLabel();
        Txt_TituloJuego3Psicologo = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txA_text_info1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txA_text_info2 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        Txt_MoralejaJuego3Psicologo = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        btn_ingresar1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_ingresar3 = new javax.swing.JButton();
        btn_ingresar4 = new javax.swing.JButton();
        btn_ingresar2 = new javax.swing.JButton();
        btn_ingresar = new javax.swing.JButton();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        Fondo1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenu3puntitosPsicologo = new javax.swing.JMenu();
        JMnItmCerrarPsicologo = new javax.swing.JMenuItem();
        JMnPgPrinPsicolo = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setDoubleBuffered(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(623, 1533));
        jPanel3.setPreferredSize(new java.awt.Dimension(623, 1533));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblInfor2Niño.setFont(new java.awt.Font("Rockwell Nova", 1, 14)); // NOI18N
        LblInfor2Niño.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblInfor2Niño.setText("Juego del Laberinto");
        jPanel3.add(LblInfor2Niño, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 170, -1));

        imagen_1_Laberinto.setForeground(new java.awt.Color(204, 204, 204));
        imagen_1_Laberinto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen_1_Laberinto.setText(" Ingresar Imagen");
        imagen_1_Laberinto.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(imagen_1_Laberinto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 260, 190));

        btn_Ingresar_imagen1.setText("Ingresar Imagen");
        btn_Ingresar_imagen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ingresar_imagen1ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Ingresar_imagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 160, -1));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 170, 10));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setText("Ingrese la respuesta que es correcta:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 260, 10));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 260, 10));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setText("Ingrese la imagen del laberinto");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 570, 10));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setText("Ingrese la respuesta que es correcta:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 1040, -1, -1));

        btn_Ingresar_imagen2.setText("Ingresar Imagen");
        btn_Ingresar_imagen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ingresar_imagen2ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Ingresar_imagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 680, 160, -1));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 670, 260, 10));

        imagen_1_Laberinto1.setForeground(new java.awt.Color(204, 204, 204));
        imagen_1_Laberinto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen_1_Laberinto1.setText(" Ingresar Imagen");
        imagen_1_Laberinto1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(imagen_1_Laberinto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 260, 190));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 260, 10));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel9.setText("Ingrese la imagen del laberinto");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 190, 10));

        LblInfor2Niño1.setFont(new java.awt.Font("Rockwell Nova", 1, 14)); // NOI18N
        LblInfor2Niño1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblInfor2Niño1.setText("Juego de las diferencias");
        jPanel3.add(LblInfor2Niño1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 190, -1));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1190, 560, 10));
        jPanel3.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 750, 220, 10));

        LblInfor2Niño2.setFont(new java.awt.Font("Rockwell Nova", 1, 14)); // NOI18N
        LblInfor2Niño2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblInfor2Niño2.setText("Juego de Responde lo correcto");
        jPanel3.add(LblInfor2Niño2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 730, 240, -1));

        Txt_TituloJuego3Psicologo.setForeground(new java.awt.Color(102, 102, 102));
        Txt_TituloJuego3Psicologo.setText("Ingrese el Titulo");
        Txt_TituloJuego3Psicologo.setBorder(null);
        Txt_TituloJuego3Psicologo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_TituloJuego3PsicologoMousePressed(evt);
            }
        });
        jPanel3.add(Txt_TituloJuego3Psicologo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 790, 230, 20));
        jPanel3.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 810, 230, 10));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel5.setText("Ingrese el texto de la primera parte del juego 3:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 820, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel10.setText("Titulo del Juego Número 3:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 770, -1, -1));

        txA_text_info1.setColumns(20);
        txA_text_info1.setRows(5);
        txA_text_info1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane3.setViewportView(txA_text_info1);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 850, 270, 170));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel11.setText("Ingrese la respuesta que es correcta:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, -1, -1));

        txA_text_info2.setColumns(20);
        txA_text_info2.setRows(5);
        txA_text_info2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane4.setViewportView(txA_text_info2);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 850, 260, 170));

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel12.setText("Ingrese el texto de la moraleja del juego 3:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 780, -1, -1));

        Txt_MoralejaJuego3Psicologo.setForeground(new java.awt.Color(102, 102, 102));
        Txt_MoralejaJuego3Psicologo.setText("Ingrese el Titulo");
        Txt_MoralejaJuego3Psicologo.setBorder(null);
        Txt_MoralejaJuego3Psicologo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_MoralejaJuego3PsicologoMousePressed(evt);
            }
        });
        jPanel3.add(Txt_MoralejaJuego3Psicologo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 800, 260, 20));
        jPanel3.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 820, 260, 10));
        jPanel3.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, 560, 10));

        btn_ingresar1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_ingresar1.setText("Ingresar");
        btn_ingresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ingresar1MouseClicked(evt);
            }
        });
        btn_ingresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_ingresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 1160, 100, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Imagen 1", "Respuesta 1", "Imagen 2", "Respuesta 2", "Titulo ", "Moraleja", "Respuesta 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable1);

        jPanel3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1220, 590, 220));

        btn_ingresar3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ingresar3.setText("Consultar");
        btn_ingresar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ingresar3MouseClicked(evt);
            }
        });
        btn_ingresar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresar3ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_ingresar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1460, 100, -1));

        btn_ingresar4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ingresar4.setText("Modificar");
        btn_ingresar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ingresar4MouseClicked(evt);
            }
        });
        btn_ingresar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresar4ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_ingresar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1460, 100, -1));

        btn_ingresar2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ingresar2.setText("Actualizar");
        btn_ingresar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ingresar2MouseClicked(evt);
            }
        });
        btn_ingresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresar2ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_ingresar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 1460, 100, -1));

        btn_ingresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ingresar.setText("Eliminar");
        btn_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ingresarMouseClicked(evt);
            }
        });
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 1460, 100, -1));
        jPanel3.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1500, 600, 10));

        jScrollPane1.setViewportView(jPanel3);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 280));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 640, 280));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Creación de los Mini juegos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 260, -1));

        Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoJuegosRepresentante.png"))); // NOI18N
        Fondo1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-870, -50, 1670, 590));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoClaro.jpg"))); // NOI18N
        Fondo.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 800, 500));

        JMenu3puntitosPsicologo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TresPuntitos.png"))); // NOI18N

        JMnItmCerrarPsicologo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        JMnItmCerrarPsicologo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CerrarSesion.png"))); // NOI18N
        JMnItmCerrarPsicologo.setText("Cerrar Sesión");
        JMnItmCerrarPsicologo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMnItmCerrarPsicologoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JMnItmCerrarPsicologoMousePressed(evt);
            }
        });
        JMenu3puntitosPsicologo.add(JMnItmCerrarPsicologo);

        jMenuBar1.add(JMenu3puntitosPsicologo);

        JMnPgPrinPsicolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Casita.png"))); // NOI18N
        JMnPgPrinPsicolo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMnPgPrinPsicoloMouseClicked(evt);
            }
        });
        jMenuBar1.add(JMnPgPrinPsicolo);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMnItmCerrarPsicologoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMnItmCerrarPsicologoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JMnItmCerrarPsicologoMouseClicked

    private void JMnItmCerrarPsicologoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMnItmCerrarPsicologoMousePressed
        InicioPsicologo loginPsicologo = new InicioPsicologo();
        loginPsicologo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JMnItmCerrarPsicologoMousePressed

    private void JMnPgPrinPsicoloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMnPgPrinPsicoloMouseClicked
        PagPrincipalPsicologo principal = new PagPrincipalPsicologo();
        principal.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_JMnPgPrinPsicoloMouseClicked

    private void btn_Ingresar_imagen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ingresar_imagen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Ingresar_imagen1ActionPerformed

    private void btn_Ingresar_imagen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ingresar_imagen2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Ingresar_imagen2ActionPerformed

    private void Txt_TituloJuego3PsicologoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_TituloJuego3PsicologoMousePressed
        if (Txt_TituloJuego3Psicologo.getText().equals("Ingrese el Titulo")) {
            Txt_TituloJuego3Psicologo.setText("");
            Txt_TituloJuego3Psicologo.setForeground(Color.black);
        }
        if (Txt_MoralejaJuego3Psicologo.getText().isEmpty()) {
            Txt_MoralejaJuego3Psicologo.setText("Ingrese el Titulo");
            Txt_MoralejaJuego3Psicologo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_Txt_TituloJuego3PsicologoMousePressed

    private void Txt_MoralejaJuego3PsicologoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_MoralejaJuego3PsicologoMousePressed
        if (Txt_MoralejaJuego3Psicologo.getText().equals("Ingrese el Titulo")) {
            Txt_MoralejaJuego3Psicologo.setText("");
            Txt_MoralejaJuego3Psicologo.setForeground(Color.black);
        }
        if (Txt_TituloJuego3Psicologo.getText().isEmpty()) {
            Txt_TituloJuego3Psicologo.setText("Ingrese el Titulo");
            Txt_TituloJuego3Psicologo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_Txt_MoralejaJuego3PsicologoMousePressed

    private void btn_ingresar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ingresar1MouseClicked

    private void btn_ingresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ingresar1ActionPerformed

    private void btn_ingresar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresar3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ingresar3MouseClicked

    private void btn_ingresar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ingresar3ActionPerformed

    private void btn_ingresar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresar4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ingresar4MouseClicked

    private void btn_ingresar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ingresar4ActionPerformed

    private void btn_ingresar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresar2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ingresar2MouseClicked

    private void btn_ingresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ingresar2ActionPerformed

    private void btn_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresarMouseClicked
        //
        //        try {
            //            Informacion info = new Informacion();
            //            cod = Crear_codigo_info(Base);
            //            info.setCod_Info(cod);
            //
            //            info.setTitulo_Info(txt_Titulo.getText());
            //            info.setTexto_Info(txA_text_info.getText());
            //            info.setImagen(imagen);
            //            Base.store(info);
            //            if (RegistrarsePsicologo.cedula_pasada_interfaz==null) {
                //                javax.swing.JOptionPane.showMessageDialog(this, "La cedula estraida del psicologo esta vacia");
                //            }
            //
            //            Ingresa_Info_Publicacion(Base, Crear_codigo_public(Base), cod, RegistrarsePsicologo.cedula_pasada_interfaz, new Date());
            //            javax.swing.JOptionPane.showMessageDialog(this, "Se guardo la Informacion");
            //
            //            MostrarDatos(Base);
            //            Vaciar_datos();
            //        } catch (Exception e) {
            //
            //        }finally{
            //            Base.close();
            //
            //        }
    }//GEN-LAST:event_btn_ingresarMouseClicked

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed

    }//GEN-LAST:event_btn_ingresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagCrudJuegosPsicologo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagCrudJuegosPsicologo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagCrudJuegosPsicologo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagCrudJuegosPsicologo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagCrudJuegosPsicologo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Fondo1;
    private javax.swing.JMenu JMenu3puntitosPsicologo;
    private javax.swing.JMenuItem JMnItmCerrarPsicologo;
    private javax.swing.JMenu JMnPgPrinPsicolo;
    private javax.swing.JLabel LblInfor2Niño;
    private javax.swing.JLabel LblInfor2Niño1;
    private javax.swing.JLabel LblInfor2Niño2;
    private javax.swing.JTextField Txt_MoralejaJuego3Psicologo;
    private javax.swing.JTextField Txt_TituloJuego3Psicologo;
    private javax.swing.JButton btn_Ingresar_imagen1;
    private javax.swing.JButton btn_Ingresar_imagen2;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_ingresar1;
    private javax.swing.JButton btn_ingresar2;
    private javax.swing.JButton btn_ingresar3;
    private javax.swing.JButton btn_ingresar4;
    private javax.swing.JLabel imagen_1_Laberinto;
    private javax.swing.JLabel imagen_1_Laberinto1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea txA_text_info1;
    private javax.swing.JTextArea txA_text_info2;
    // End of variables declaration//GEN-END:variables
}
