/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

/**
 *
 * @author mauca
 */
import com.db4o.*;

public class PagInfPariente extends javax.swing.JFrame {

    ObjectContainer Base;
    
    public PagInfPariente() {
        initComponents();
            Base = Db4o.openFile("src/BBDD/BaseDat.yap");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        LblInfor2Niño = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        LblTitulo1InfPariente = new javax.swing.JLabel();
        LblImagen1InfoPariente = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        LblTitulo2InfPariente = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        LblImagen2InfoPariente = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        Txt3InfPariente = new javax.swing.JTextArea();
        jSeparator10 = new javax.swing.JSeparator();
        LblTitulo3InfPariente = new javax.swing.JLabel();
        LblImagen3InfoPariente = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        Txt1InfPariente = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Txt2InfPariente = new javax.swing.JTextArea();
        LblInformacionPsicologo2 = new javax.swing.JLabel();
        LblInformacionPsicologo1 = new javax.swing.JLabel();
        Fondo1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        MenuCuentosNiño = new javax.swing.JMenuBar();
        JMenu3puntitosNiño = new javax.swing.JMenu();
        JMnItmCerrarPariente = new javax.swing.JMenuItem();
        JMnPgPrinPariente = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setText("x");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 40, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setDoubleBuffered(true);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(null);
        jScrollPane3.setDoubleBuffered(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMinimumSize(new java.awt.Dimension(593, 1034));
        jPanel4.setPreferredSize(new java.awt.Dimension(593, 1034));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblInfor2Niño.setFont(new java.awt.Font("Rockwell Nova", 1, 18)); // NOI18N
        LblInfor2Niño.setText("INFORMACIÓN DEL BULLYING");
        jPanel4.add(LblInfor2Niño, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 310, -1));

        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 260, 10));

        LblTitulo1InfPariente.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        LblTitulo1InfPariente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(LblTitulo1InfPariente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 260, 20));
        jPanel4.add(LblImagen1InfoPariente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 250, 180));

        jSeparator4.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 260, 10));

        jSeparator5.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 250, 10));

        jSeparator6.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 530, 10));

        LblTitulo2InfPariente.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        LblTitulo2InfPariente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(LblTitulo2InfPariente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 260, 20));

        jSeparator7.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 260, 10));

        jSeparator8.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 750, 530, 10));
        jPanel4.add(LblImagen2InfoPariente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 530, 180));

        jSeparator9.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 1020, 260, 10));

        Txt3InfPariente.setColumns(20);
        Txt3InfPariente.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        Txt3InfPariente.setLineWrap(true);
        Txt3InfPariente.setRows(5);
        Txt3InfPariente.setWrapStyleWord(true);
        Txt3InfPariente.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Txt3InfPariente.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Txt3InfPariente.setEnabled(false);
        jScrollPane4.setViewportView(Txt3InfPariente);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 810, 260, 200));

        jSeparator10.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 800, 260, 10));

        LblTitulo3InfPariente.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        LblTitulo3InfPariente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(LblTitulo3InfPariente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 780, 260, 20));
        jPanel4.add(LblImagen3InfoPariente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 810, 250, 200));

        jSeparator11.setForeground(new java.awt.Color(153, 153, 153));
        jPanel4.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1020, 250, 10));

        Txt1InfPariente.setColumns(20);
        Txt1InfPariente.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        Txt1InfPariente.setLineWrap(true);
        Txt1InfPariente.setRows(5);
        Txt1InfPariente.setWrapStyleWord(true);
        Txt1InfPariente.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Txt1InfPariente.setEnabled(false);
        jScrollPane5.setViewportView(Txt1InfPariente);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 260, 170));

        Txt2InfPariente.setColumns(20);
        Txt2InfPariente.setLineWrap(true);
        Txt2InfPariente.setRows(5);
        Txt2InfPariente.setWrapStyleWord(true);
        Txt2InfPariente.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Txt2InfPariente.setEnabled(false);
        jScrollPane2.setViewportView(Txt2InfPariente);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 350, 540, 180));

        jScrollPane3.setViewportView(jPanel4);

        jScrollPane1.setViewportView(jScrollPane3);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 280));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 610, 280));

        LblInformacionPsicologo2.setFont(new java.awt.Font("Rockwell Nova", 1, 18)); // NOI18N
        LblInformacionPsicologo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblInformacionPsicologo2.setText("INFORMACIÓN");
        jPanel2.add(LblInformacionPsicologo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 350, 30));

        LblInformacionPsicologo1.setFont(new java.awt.Font("Rockwell Nova", 1, 18)); // NOI18N
        LblInformacionPsicologo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblInformacionPsicologo1.setText("BIENVENIDOS AL AREA DE :");
        jPanel2.add(LblInformacionPsicologo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 350, 20));

        Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoInfRepresentante.png"))); // NOI18N
        Fondo1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel2.add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-870, -10, 1690, 510));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoClaro.jpg"))); // NOI18N
        Fondo.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel2.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 800, 500));

        JMenu3puntitosNiño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TresPuntitos.png"))); // NOI18N

        JMnItmCerrarPariente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        JMnItmCerrarPariente.setBackground(new java.awt.Color(255, 255, 255));
        JMnItmCerrarPariente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CerrarSesion.png"))); // NOI18N
        JMnItmCerrarPariente.setText("Cerrar Sesión");
        JMnItmCerrarPariente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JMnItmCerrarParienteMousePressed(evt);
            }
        });
        JMenu3puntitosNiño.add(JMnItmCerrarPariente);

        MenuCuentosNiño.add(JMenu3puntitosNiño);

        JMnPgPrinPariente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Casita.png"))); // NOI18N
        JMnPgPrinPariente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMnPgPrinParienteMouseClicked(evt);
            }
        });
        MenuCuentosNiño.add(JMnPgPrinPariente);

        setJMenuBar(MenuCuentosNiño);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMnItmCerrarParienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMnItmCerrarParienteMousePressed
        Base.close();
            InicioRepresentante loginrepre = new InicioRepresentante();
                loginrepre.setVisible(true);
                    this.setVisible(false);
    }//GEN-LAST:event_JMnItmCerrarParienteMousePressed

    private void JMnPgPrinParienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMnPgPrinParienteMouseClicked
        Base.close();
            PagPrincipalRepresentante principalrepresetante = new PagPrincipalRepresentante();
                principalrepresetante.setVisible(true);
                    this.setVisible(false);
    }//GEN-LAST:event_JMnPgPrinParienteMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed

        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagInfPariente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagInfPariente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagInfPariente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagInfPariente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagInfPariente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Fondo1;
    private javax.swing.JMenu JMenu3puntitosNiño;
    private javax.swing.JMenuItem JMnItmCerrarPariente;
    private javax.swing.JMenu JMnPgPrinPariente;
    private javax.swing.JLabel LblImagen1InfoPariente;
    private javax.swing.JLabel LblImagen2InfoPariente;
    private javax.swing.JLabel LblImagen3InfoPariente;
    private javax.swing.JLabel LblInfor2Niño;
    private javax.swing.JLabel LblInformacionPsicologo1;
    private javax.swing.JLabel LblInformacionPsicologo2;
    private javax.swing.JLabel LblTitulo1InfPariente;
    private javax.swing.JLabel LblTitulo2InfPariente;
    private javax.swing.JLabel LblTitulo3InfPariente;
    private javax.swing.JMenuBar MenuCuentosNiño;
    private javax.swing.JTextArea Txt1InfPariente;
    private javax.swing.JTextArea Txt2InfPariente;
    private javax.swing.JTextArea Txt3InfPariente;
    private javax.swing.JButton btnExit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
