/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

/**
 *
 * @author mauca
 */
public class PagInfNiño extends javax.swing.JFrame {

    /**
     * Creates new form PagInfNiño
     */
    public PagInfNiño() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        PnlPrincipalInfNiño = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        LblInfor2Niño = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        LblTitulo1InfNiño = new javax.swing.JLabel();
        LblImagen1InfoNiño = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        LblTitulo2InfNiño = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        LblImagen2InfoNiño = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        Txt3InfNiño = new javax.swing.JTextArea();
        jSeparator10 = new javax.swing.JSeparator();
        LblTitulo3InfNiño = new javax.swing.JLabel();
        LblImagen3InfoNiño = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        LblImagen4InfoNiño = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        LblImagen5InfoNiño = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        Txt1InfNiño = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Txt2InfNiño = new javax.swing.JTextArea();
        BtnRegresar1 = new javax.swing.JButton();
        LblInformacionNiño = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Fondo1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        MenuInfNiño = new javax.swing.JMenuBar();
        JMenu3puntitosNiño = new javax.swing.JMenu();
        JMnItmCerrarNiño = new javax.swing.JMenuItem();
        JMnPgPrinNiño = new javax.swing.JMenu();

        jSeparator3.setForeground(new java.awt.Color(153, 153, 153));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlPrincipalInfNiño.setBackground(new java.awt.Color(255, 255, 255));
        PnlPrincipalInfNiño.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setDoubleBuffered(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblInfor2Niño.setFont(new java.awt.Font("Rockwell Nova", 1, 18)); // NOI18N
        LblInfor2Niño.setText("INFORMACIÓN DEL BULLYING");
        jPanel1.add(LblInfor2Niño, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 310, -1));

        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 260, 10));

        LblTitulo1InfNiño.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jPanel1.add(LblTitulo1InfNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, 20));
        jPanel1.add(LblImagen1InfoNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 250, 180));

        jSeparator4.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 130, 10));

        jSeparator5.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 250, 10));

        jSeparator6.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 530, 10));

        LblTitulo2InfNiño.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jPanel1.add(LblTitulo2InfNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 130, 20));

        jSeparator7.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 130, 10));

        jSeparator8.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 750, 530, 10));
        jPanel1.add(LblImagen2InfoNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 530, 180));

        jSeparator9.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 1020, 260, 10));

        Txt3InfNiño.setColumns(20);
        Txt3InfNiño.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        Txt3InfNiño.setLineWrap(true);
        Txt3InfNiño.setRows(5);
        Txt3InfNiño.setWrapStyleWord(true);
        Txt3InfNiño.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Txt3InfNiño.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Txt3InfNiño.setEnabled(false);
        jScrollPane4.setViewportView(Txt3InfNiño);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 810, 260, 200));

        jSeparator10.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 800, 240, 10));

        LblTitulo3InfNiño.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jPanel1.add(LblTitulo3InfNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 780, 240, 20));
        jPanel1.add(LblImagen3InfoNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 810, 250, 200));

        jSeparator11.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1020, 250, 10));
        jPanel1.add(LblImagen4InfoNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1050, 250, 200));

        jSeparator12.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1260, 250, 10));
        jPanel1.add(LblImagen5InfoNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 1050, 250, 200));

        jSeparator13.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 1260, 250, 10));

        Txt1InfNiño.setColumns(20);
        Txt1InfNiño.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        Txt1InfNiño.setLineWrap(true);
        Txt1InfNiño.setRows(5);
        Txt1InfNiño.setWrapStyleWord(true);
        Txt1InfNiño.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Txt1InfNiño.setEnabled(false);
        jScrollPane5.setViewportView(Txt1InfNiño);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 260, 170));

        Txt2InfNiño.setColumns(20);
        Txt2InfNiño.setLineWrap(true);
        Txt2InfNiño.setRows(5);
        Txt2InfNiño.setWrapStyleWord(true);
        Txt2InfNiño.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Txt2InfNiño.setEnabled(false);
        jScrollPane2.setViewportView(Txt2InfNiño);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 350, 540, 180));

        jScrollPane1.setViewportView(jPanel1);

        PnlPrincipalInfNiño.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 610, 340));

        BtnRegresar1.setBackground(new java.awt.Color(255, 255, 255));
        BtnRegresar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        BtnRegresar1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        BtnRegresar1.setOpaque(false);
        BtnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresar1ActionPerformed(evt);
            }
        });
        PnlPrincipalInfNiño.add(BtnRegresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 40, 30));

        LblInformacionNiño.setFont(new java.awt.Font("Rockwell Nova", 1, 14)); // NOI18N
        LblInformacionNiño.setText("BIENVENIDOS AL AREA DE INFORMACIÓN");
        PnlPrincipalInfNiño.add(LblInformacionNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 350, 20));
        PnlPrincipalInfNiño.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 410, 20));

        Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoInfoNiño.png"))); // NOI18N
        Fondo1.setPreferredSize(new java.awt.Dimension(800, 500));
        PnlPrincipalInfNiño.add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-870, 0, 1690, 510));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoClaro.jpg"))); // NOI18N
        Fondo.setPreferredSize(new java.awt.Dimension(800, 500));
        PnlPrincipalInfNiño.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        getContentPane().add(PnlPrincipalInfNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 800, 500));

        JMenu3puntitosNiño.setBackground(new java.awt.Color(255, 255, 255));
        JMenu3puntitosNiño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TresPuntitos.png"))); // NOI18N

        JMnItmCerrarNiño.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        JMnItmCerrarNiño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CerrarSesion.png"))); // NOI18N
        JMnItmCerrarNiño.setText("Cerrar Sesión");
        JMenu3puntitosNiño.add(JMnItmCerrarNiño);

        MenuInfNiño.add(JMenu3puntitosNiño);

        JMnPgPrinNiño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Casita.png"))); // NOI18N
        JMnPgPrinNiño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMnPgPrinNiñoMouseClicked(evt);
            }
        });
        JMnPgPrinNiño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMnPgPrinNiñoActionPerformed(evt);
            }
        });
        MenuInfNiño.add(JMnPgPrinNiño);

        setJMenuBar(MenuInfNiño);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresar1ActionPerformed
        PagPrincipalNiño pagprincipalniño = new PagPrincipalNiño();
        pagprincipalniño.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnRegresar1ActionPerformed

    private void JMnPgPrinNiñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMnPgPrinNiñoActionPerformed
        
    }//GEN-LAST:event_JMnPgPrinNiñoActionPerformed

    private void JMnPgPrinNiñoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMnPgPrinNiñoMouseClicked
        PagPrincipalNiño principalniño = new PagPrincipalNiño();
        principalniño.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JMnPgPrinNiñoMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegresar1;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Fondo1;
    private javax.swing.JMenu JMenu3puntitosNiño;
    private javax.swing.JMenuItem JMnItmCerrarNiño;
    private javax.swing.JMenu JMnPgPrinNiño;
    private javax.swing.JLabel LblImagen1InfoNiño;
    private javax.swing.JLabel LblImagen2InfoNiño;
    private javax.swing.JLabel LblImagen3InfoNiño;
    private javax.swing.JLabel LblImagen4InfoNiño;
    private javax.swing.JLabel LblImagen5InfoNiño;
    private javax.swing.JLabel LblInfor2Niño;
    private javax.swing.JLabel LblInformacionNiño;
    private javax.swing.JLabel LblTitulo1InfNiño;
    private javax.swing.JLabel LblTitulo2InfNiño;
    private javax.swing.JLabel LblTitulo3InfNiño;
    private javax.swing.JMenuBar MenuInfNiño;
    private javax.swing.JPanel PnlPrincipalInfNiño;
    private javax.swing.JTextArea Txt1InfNiño;
    private javax.swing.JTextArea Txt2InfNiño;
    private javax.swing.JTextArea Txt3InfNiño;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
