/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

/**
 *
 * @author mauca
 */
public class PagJuego1Niño extends javax.swing.JFrame {

    /**
     * Creates new form PagJuego1Niño
     */
    public PagJuego1Niño() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGrupLaberinRespNiño = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        LblTituloLabeNiño2 = new javax.swing.JLabel();
        LblPreguntaLabeNiño = new javax.swing.JLabel();
        LblImaNiñoLaberintoJueg = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        LblTituloLabeNiño1 = new javax.swing.JLabel();
        LblSubTituLabeJuegNiño = new javax.swing.JLabel();
        BtnALabeNiño1 = new javax.swing.JRadioButton();
        BtnALabeNiño2 = new javax.swing.JRadioButton();
        BtnALabeNiño3 = new javax.swing.JRadioButton();
        BtnRegresar1 = new javax.swing.JButton();
        LblInformacionNiño1 = new javax.swing.JLabel();
        LblInformacionNiño = new javax.swing.JLabel();
        Fondo1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        MenuJuego1Niño = new javax.swing.JMenuBar();
        JMenu3puntitosNiño = new javax.swing.JMenu();
        JMnItmCerrarNiño = new javax.swing.JMenuItem();
        JMnPgPrinNiño = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setDoubleBuffered(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(520, 486));
        jPanel3.setPreferredSize(new java.awt.Dimension(520, 486));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblTituloLabeNiño2.setFont(new java.awt.Font("Rockwell Nova", 1, 18)); // NOI18N
        LblTituloLabeNiño2.setText("EL LABERINTO");
        jPanel3.add(LblTituloLabeNiño2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 160, -1));

        LblPreguntaLabeNiño.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        LblPreguntaLabeNiño.setText("¿Cuál de estos caminos es el correcto?");
        jPanel3.add(LblPreguntaLabeNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 230, 20));

        LblImaNiñoLaberintoJueg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblImaNiñoLaberintoJueg.setText("      ");
        LblImaNiñoLaberintoJueg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(LblImaNiñoLaberintoJueg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 440, 280));

        jSeparator4.setForeground(new java.awt.Color(153, 153, 153));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 190, 10));

        jSeparator5.setForeground(new java.awt.Color(153, 153, 153));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 440, 10));

        LblTituloLabeNiño1.setFont(new java.awt.Font("Rockwell Nova", 1, 18)); // NOI18N
        LblTituloLabeNiño1.setText("HOY TENEMOS EL JUEGO DE:");
        jPanel3.add(LblTituloLabeNiño1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 330, -1));

        LblSubTituLabeJuegNiño.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        LblSubTituLabeJuegNiño.setText("Encuentra El Camino Correcto");
        jPanel3.add(LblSubTituLabeJuegNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 180, 20));

        BtnGrupLaberinRespNiño.add(BtnALabeNiño1);
        BtnALabeNiño1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        BtnALabeNiño1.setText("1. A");
        jPanel3.add(BtnALabeNiño1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 50, 30));

        BtnGrupLaberinRespNiño.add(BtnALabeNiño2);
        BtnALabeNiño2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        BtnALabeNiño2.setText("2. B");
        jPanel3.add(BtnALabeNiño2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 50, 30));

        BtnGrupLaberinRespNiño.add(BtnALabeNiño3);
        BtnALabeNiño3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        BtnALabeNiño3.setText("3. C");
        jPanel3.add(BtnALabeNiño3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 50, 30));

        jScrollPane1.setViewportView(jPanel3);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 240));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 570, 240));

        BtnRegresar1.setBackground(new java.awt.Color(255, 255, 255));
        BtnRegresar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        BtnRegresar1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        BtnRegresar1.setOpaque(false);
        BtnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresar1ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 40, 30));

        LblInformacionNiño1.setFont(new java.awt.Font("Rockwell Nova", 1, 18)); // NOI18N
        LblInformacionNiño1.setText("BIENVENIDOS AL JUEGO DEL:");
        jPanel1.add(LblInformacionNiño1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 300, 20));

        LblInformacionNiño.setFont(new java.awt.Font("Rockwell Nova", 1, 18)); // NOI18N
        LblInformacionNiño.setText("LABERINTO");
        jPanel1.add(LblInformacionNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 120, 20));

        Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoJuego1Niño.png"))); // NOI18N
        Fondo1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-870, 0, 1690, 510));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoClaro.jpg"))); // NOI18N
        Fondo.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 800, 500));

        MenuJuego1Niño.setBackground(new java.awt.Color(255, 255, 255));

        JMenu3puntitosNiño.setBackground(new java.awt.Color(255, 255, 255));
        JMenu3puntitosNiño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TresPuntitos.png"))); // NOI18N

        JMnItmCerrarNiño.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        JMnItmCerrarNiño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CerrarSesion.png"))); // NOI18N
        JMnItmCerrarNiño.setText("Cerrar Sesión");
        JMenu3puntitosNiño.add(JMnItmCerrarNiño);

        MenuJuego1Niño.add(JMenu3puntitosNiño);

        JMnPgPrinNiño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Casita.png"))); // NOI18N
        JMnPgPrinNiño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMnPgPrinNiñoMouseClicked(evt);
            }
        });
        MenuJuego1Niño.add(JMnPgPrinNiño);

        setJMenuBar(MenuJuego1Niño);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresar1ActionPerformed
        PagMiniJuegoNiño Juego1 = new PagMiniJuegoNiño();
        Juego1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnRegresar1ActionPerformed

    private void JMnPgPrinNiñoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMnPgPrinNiñoMouseClicked
        PagPrincipalNiñ principalniño = new PagPrincipalNiñ();
            principalniño.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_JMnPgPrinNiñoMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BtnALabeNiño1;
    private javax.swing.JRadioButton BtnALabeNiño2;
    private javax.swing.JRadioButton BtnALabeNiño3;
    private javax.swing.ButtonGroup BtnGrupLaberinRespNiño;
    private javax.swing.JButton BtnRegresar1;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Fondo1;
    private javax.swing.JMenu JMenu3puntitosNiño;
    private javax.swing.JMenuItem JMnItmCerrarNiño;
    private javax.swing.JMenu JMnPgPrinNiño;
    private javax.swing.JLabel LblImaNiñoLaberintoJueg;
    private javax.swing.JLabel LblInformacionNiño;
    private javax.swing.JLabel LblInformacionNiño1;
    private javax.swing.JLabel LblPreguntaLabeNiño;
    private javax.swing.JLabel LblSubTituLabeJuegNiño;
    private javax.swing.JLabel LblTituloLabeNiño1;
    private javax.swing.JLabel LblTituloLabeNiño2;
    private javax.swing.JMenuBar MenuJuego1Niño;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
