/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Clases.*;
import Login.PagPrincipalRepresentante;
import Login.RegistrarseGeneral;

import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import com.db4o.query.Query;
import java.awt.Color;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author mauca
 */
public class RegistrarsePsicologo extends javax.swing.JFrame {

    public static String cedula_pasada_interfaz;
    ObjectContainer Base;
    Date Nacimiento;

    /**
     * Creates new form RegistrarsePsicologo
     */
    public RegistrarsePsicologo() {
        initComponents();
        Base = Db4o.openFile("src/BBDD/BaseDat.yap");
        Nacionalidades_ingr(Base);
        Discapacidad_ingr(Base);
        Especializacion_ingr(Base);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGpDiscaPsicol = new javax.swing.ButtonGroup();
        BtnGrpSexoPsicol = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Psicologo = new javax.swing.JLabel();
        Femenino = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        Discapacidad = new javax.swing.JLabel();
        Sexo = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        TxtApelliPsicol = new javax.swing.JTextField();
        ConfirmarContraseña = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        TxtNomPsicol = new javax.swing.JTextField();
        Nombre = new javax.swing.JLabel();
        FechaNacimiento = new javax.swing.JLabel();
        DateFechaNaciPsicol = new com.toedter.calendar.JDateChooser();
        jSeparator3 = new javax.swing.JSeparator();
        Registrarse = new javax.swing.JLabel();
        TxtCeduPsicol = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Cedula = new javax.swing.JLabel();
        Nacionalidad_lbl = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        TxtDireccPsicol = new javax.swing.JTextField();
        Direccion = new javax.swing.JLabel();
        NuevaContraseña = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        BtnRegistrarsePsicol = new javax.swing.JButton();
        Apellidos = new javax.swing.JLabel();
        NvContraPsicol = new javax.swing.JPasswordField();
        jSeparator15 = new javax.swing.JSeparator();
        CmbBxNacionalidad3Psicol = new javax.swing.JComboBox<>();
        Especializacion = new javax.swing.JLabel();
        TxtTelefono = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        CfContraPsicol = new javax.swing.JPasswordField();
        cbx_discapacidad = new javax.swing.JComboBox<>();
        Especializacion1 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        Especializacion2 = new javax.swing.JLabel();
        TxtCorreoPsicologo = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        Especializacion3 = new javax.swing.JLabel();
        sp_años = new javax.swing.JSpinner();
        TxtEspecializacionPsicol1 = new javax.swing.JComboBox<>();
        BtnRegresar = new javax.swing.JButton();
        Fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Psicologo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/terapia.png"))); // NOI18N
        jPanel2.add(Psicologo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, 60));

        BtnGrpSexoPsicol.add(Femenino);
        Femenino.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        Femenino.setText("Femenino");
        jPanel2.add(Femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        BtnGrpSexoPsicol.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jRadioButton3.setText("Masculino");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        Discapacidad.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Discapacidad.setText("Discapacidad:");
        jPanel2.add(Discapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, -1, -1));

        Sexo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Sexo.setText("Sexo:");
        jPanel2.add(Sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 159, -1, 30));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 80, 10));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 80, 10));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 170, 10));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 170, 10));

        TxtApelliPsicol.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TxtApelliPsicol.setForeground(new java.awt.Color(153, 153, 153));
        TxtApelliPsicol.setText("Ingrese sus Apellidos");
        TxtApelliPsicol.setBorder(null);
        TxtApelliPsicol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtApelliPsicolMousePressed(evt);
            }
        });
        TxtApelliPsicol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtApelliPsicolActionPerformed(evt);
            }
        });
        jPanel2.add(TxtApelliPsicol, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 170, -1));

        ConfirmarContraseña.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        ConfirmarContraseña.setText("Confrimar Contraseña:");
        jPanel2.add(ConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, 20));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 160, 10));

        TxtNomPsicol.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TxtNomPsicol.setForeground(new java.awt.Color(153, 153, 153));
        TxtNomPsicol.setText("Ingrese sus Nombres");
        TxtNomPsicol.setBorder(null);
        TxtNomPsicol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtNomPsicolMousePressed(evt);
            }
        });
        TxtNomPsicol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomPsicolActionPerformed(evt);
            }
        });
        jPanel2.add(TxtNomPsicol, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 160, -1));

        Nombre.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Nombre.setText("Nombres:");
        jPanel2.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        FechaNacimiento.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        FechaNacimiento.setText("Fecha de Nacimiento:");
        jPanel2.add(FechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));
        jPanel2.add(DateFechaNaciPsicol, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 160, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 160, 10));

        Registrarse.setFont(new java.awt.Font("Rockwell Nova", 1, 24)); // NOI18N
        Registrarse.setText("REGISTRARSE");
        jPanel2.add(Registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        TxtCeduPsicol.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TxtCeduPsicol.setForeground(new java.awt.Color(153, 153, 153));
        TxtCeduPsicol.setText("Ingrese su cedula");
        TxtCeduPsicol.setBorder(null);
        TxtCeduPsicol.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtCeduPsicolFocusLost(evt);
            }
        });
        TxtCeduPsicol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtCeduPsicolMousePressed(evt);
            }
        });
        TxtCeduPsicol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCeduPsicolActionPerformed(evt);
            }
        });
        jPanel2.add(TxtCeduPsicol, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 160, -1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 170, 10));

        Cedula.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Cedula.setText("Cedula:");
        jPanel2.add(Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        Nacionalidad_lbl.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Nacionalidad_lbl.setText("Nacionalidad:");
        jPanel2.add(Nacionalidad_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, -1));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 170, 10));
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 170, 10));

        TxtDireccPsicol.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TxtDireccPsicol.setForeground(new java.awt.Color(153, 153, 153));
        TxtDireccPsicol.setText("Ingrese su Dirección");
        TxtDireccPsicol.setBorder(null);
        TxtDireccPsicol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtDireccPsicolMousePressed(evt);
            }
        });
        TxtDireccPsicol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDireccPsicolActionPerformed(evt);
            }
        });
        jPanel2.add(TxtDireccPsicol, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 170, -1));

        Direccion.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Direccion.setText("Dirección:");
        jPanel2.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        NuevaContraseña.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        NuevaContraseña.setText("Nueva Contraseña:");
        jPanel2.add(NuevaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));
        jPanel2.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 170, 10));

        BtnRegistrarsePsicol.setText("Registrarse");
        BtnRegistrarsePsicol.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        BtnRegistrarsePsicol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarsePsicolActionPerformed(evt);
            }
        });
        jPanel2.add(BtnRegistrarsePsicol, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 120, 30));

        Apellidos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Apellidos.setText("Apellidos:");
        jPanel2.add(Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        NvContraPsicol.setForeground(new java.awt.Color(153, 153, 153));
        NvContraPsicol.setText("**********");
        NvContraPsicol.setBorder(null);
        NvContraPsicol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NvContraPsicolMousePressed(evt);
            }
        });
        NvContraPsicol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NvContraPsicolActionPerformed(evt);
            }
        });
        jPanel2.add(NvContraPsicol, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 170, -1));
        jPanel2.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 170, 10));

        CmbBxNacionalidad3Psicol.setBorder(null);
        CmbBxNacionalidad3Psicol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CmbBxNacionalidad3PsicolMousePressed(evt);
            }
        });
        CmbBxNacionalidad3Psicol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbBxNacionalidad3PsicolActionPerformed(evt);
            }
        });
        jPanel2.add(CmbBxNacionalidad3Psicol, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 170, -1));

        Especializacion.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Especializacion.setText("Años de Esperiencia:");
        jPanel2.add(Especializacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 160, -1));

        TxtTelefono.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TxtTelefono.setForeground(new java.awt.Color(153, 153, 153));
        TxtTelefono.setText("Ingrese su Telefono");
        TxtTelefono.setBorder(null);
        TxtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtTelefonoMousePressed(evt);
            }
        });
        TxtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTelefonoActionPerformed(evt);
            }
        });
        jPanel2.add(TxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 170, -1));
        jPanel2.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 160, 10));

        CfContraPsicol.setForeground(new java.awt.Color(153, 153, 153));
        CfContraPsicol.setText("**********");
        CfContraPsicol.setBorder(null);
        CfContraPsicol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CfContraPsicolMousePressed(evt);
            }
        });
        CfContraPsicol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CfContraPsicolActionPerformed(evt);
            }
        });
        jPanel2.add(CfContraPsicol, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 170, -1));

        cbx_discapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_discapacidadActionPerformed(evt);
            }
        });
        jPanel2.add(cbx_discapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 170, -1));

        Especializacion1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Especializacion1.setText("Especialización:");
        jPanel2.add(Especializacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));
        jPanel2.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 170, 10));

        Especializacion2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Especializacion2.setText("Correo:");
        jPanel2.add(Especializacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        TxtCorreoPsicologo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TxtCorreoPsicologo.setForeground(new java.awt.Color(153, 153, 153));
        TxtCorreoPsicologo.setText("Ingrese su Correo");
        TxtCorreoPsicologo.setBorder(null);
        TxtCorreoPsicologo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtCorreoPsicologoMousePressed(evt);
            }
        });
        TxtCorreoPsicologo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCorreoPsicologoActionPerformed(evt);
            }
        });
        jPanel2.add(TxtCorreoPsicologo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 170, -1));
        jPanel2.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 170, 10));

        Especializacion3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Especializacion3.setText("Telefono:");
        jPanel2.add(Especializacion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));
        jPanel2.add(sp_años, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 150, -1));

        TxtEspecializacionPsicol1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        TxtEspecializacionPsicol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEspecializacionPsicol1ActionPerformed(evt);
            }
        });
        jPanel2.add(TxtEspecializacionPsicol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 170, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 690, 420));

        BtnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        BtnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        BtnRegresar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        BtnRegresar.setOpaque(false);
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, 50, 40));

        Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoClaro.jpg"))); // NOI18N
        jPanel1.add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CfContraPsicolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CfContraPsicolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CfContraPsicolActionPerformed

    private void TxtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTelefonoActionPerformed

    private void CmbBxNacionalidad3PsicolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbBxNacionalidad3PsicolActionPerformed


    }//GEN-LAST:event_CmbBxNacionalidad3PsicolActionPerformed

    private void NvContraPsicolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NvContraPsicolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NvContraPsicolActionPerformed

    private void TxtDireccPsicolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDireccPsicolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDireccPsicolActionPerformed

    private void TxtCeduPsicolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCeduPsicolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCeduPsicolActionPerformed

    private void TxtNomPsicolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomPsicolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomPsicolActionPerformed

    private void TxtApelliPsicolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtApelliPsicolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtApelliPsicolActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        RegistrarseGeneral general = new RegistrarseGeneral();
        general.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void TxtNomPsicolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtNomPsicolMousePressed
        if (TxtNomPsicol.getText().equals("Ingrese sus Nombres")) {
            TxtNomPsicol.setText("");
            TxtNomPsicol.setForeground(Color.black);
        }

        if (TxtApelliPsicol.getText().isEmpty()) {
            TxtApelliPsicol.setText("Ingrese sus Apellidos");
            TxtApelliPsicol.setForeground(Color.gray);
        }

        if (TxtTelefono.getText().isEmpty()) {
            TxtTelefono.setText("Ingrese su Telefono");
            TxtTelefono.setForeground(Color.gray);
        }
        if (TxtCeduPsicol.getText().isEmpty()) {
            TxtCeduPsicol.setText("Ingrese su cedula");
            TxtCeduPsicol.setForeground(Color.gray);
        }
        if (TxtDireccPsicol.getText().isEmpty()) {
            TxtDireccPsicol.setText("Ingrese su Dirección");
            TxtDireccPsicol.setForeground(Color.gray);
        }
        
        if (TxtCorreoPsicologo.getText().isEmpty()) {
            TxtCorreoPsicologo.setText("Ingrese su Correo");
            TxtCorreoPsicologo.setForeground(Color.gray);
        }
        if (String.valueOf(NvContraPsicol.getPassword()).isEmpty()) {
            NvContraPsicol.setText("**********");
            NvContraPsicol.setForeground(Color.gray);

        }
        if (String.valueOf(CfContraPsicol.getPassword()).isEmpty()) {
            CfContraPsicol.setText("**********");
            CfContraPsicol.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_TxtNomPsicolMousePressed

    private void TxtApelliPsicolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtApelliPsicolMousePressed
        if (TxtApelliPsicol.getText().equals("Ingrese sus Apellidos")) {
            TxtApelliPsicol.setText("");
            TxtApelliPsicol.setForeground(Color.black);
        }

        if (TxtNomPsicol.getText().isEmpty()) {
            TxtNomPsicol.setText("Ingrese sus Nombres");
            TxtNomPsicol.setForeground(Color.gray);
        }

        if (TxtTelefono.getText().isEmpty()) {
            TxtTelefono.setText("Ingrese su Telefono");
            TxtTelefono.setForeground(Color.gray);
        }
        if (TxtCeduPsicol.getText().isEmpty()) {
            TxtCeduPsicol.setText("Ingrese su cedula");
            TxtCeduPsicol.setForeground(Color.gray);
        }
        if (TxtDireccPsicol.getText().isEmpty()) {
            TxtDireccPsicol.setText("Ingrese su Dirección");
            TxtDireccPsicol.setForeground(Color.gray);
        }
        
        if (TxtCorreoPsicologo.getText().isEmpty()) {
            TxtCorreoPsicologo.setText("Ingrese su Correo");
            TxtCorreoPsicologo.setForeground(Color.gray);
        }
        if (String.valueOf(NvContraPsicol.getPassword()).isEmpty()) {
            NvContraPsicol.setText("**********");
            NvContraPsicol.setForeground(Color.gray);

        }
        if (String.valueOf(CfContraPsicol.getPassword()).isEmpty()) {
            CfContraPsicol.setText("**********");
            CfContraPsicol.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_TxtApelliPsicolMousePressed

    private void TxtTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtTelefonoMousePressed

        if (TxtTelefono.getText().equals("Ingrese su Telefono")) {
            TxtTelefono.setText("");
            TxtTelefono.setForeground(Color.black);
        }

        if (TxtNomPsicol.getText().isEmpty()) {
            TxtNomPsicol.setText("Ingrese sus Nombres");
            TxtNomPsicol.setForeground(Color.gray);
        }

        if (TxtApelliPsicol.getText().isEmpty()) {
            TxtApelliPsicol.setText("Ingrese sus Apellidos");
            TxtApelliPsicol.setForeground(Color.gray);
        }
        if (TxtCeduPsicol.getText().isEmpty()) {
            TxtCeduPsicol.setText("Ingrese su cedula");
            TxtCeduPsicol.setForeground(Color.gray);
        }
        if (TxtDireccPsicol.getText().isEmpty()) {
            TxtDireccPsicol.setText("Ingrese su Dirección");
            TxtDireccPsicol.setForeground(Color.gray);
        
        if (TxtCorreoPsicologo.getText().isEmpty()) {
            TxtCorreoPsicologo.setText("Ingrese su Correo");
            TxtCorreoPsicologo.setForeground(Color.gray);
        }    
        }
        if (String.valueOf(NvContraPsicol.getPassword()).isEmpty()) {
            NvContraPsicol.setText("**********");
            NvContraPsicol.setForeground(Color.gray);

        }
        if (String.valueOf(CfContraPsicol.getPassword()).isEmpty()) {
            CfContraPsicol.setText("**********");
            CfContraPsicol.setForeground(Color.gray);
        }
    }//GEN-LAST:event_TxtTelefonoMousePressed

    private void TxtCeduPsicolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtCeduPsicolMousePressed
        if (TxtCeduPsicol.getText().equals("Ingrese su cedula")) {
            TxtCeduPsicol.setText("");
            TxtCeduPsicol.setForeground(Color.black);
        }

        if (TxtNomPsicol.getText().isEmpty()) {
            TxtNomPsicol.setText("Ingrese sus Nombres");
            TxtNomPsicol.setForeground(Color.gray);
        }

        if (TxtApelliPsicol.getText().isEmpty()) {
            TxtApelliPsicol.setText("Ingrese sus Apellidos");
            TxtApelliPsicol.setForeground(Color.gray);
        }
        if (TxtTelefono.getText().isEmpty()) {
            TxtTelefono.setText("Ingrese su Telefono");
            TxtTelefono.setForeground(Color.gray);
        }
        if (TxtDireccPsicol.getText().isEmpty()) {
            TxtDireccPsicol.setText("Ingrese su Dirección");
            TxtDireccPsicol.setForeground(Color.gray);
        }
        if (TxtCorreoPsicologo.getText().isEmpty()) {
            TxtCorreoPsicologo.setText("Ingrese su Correo");
            TxtCorreoPsicologo.setForeground(Color.gray);
        } 
        if (String.valueOf(NvContraPsicol.getPassword()).isEmpty()) {
            NvContraPsicol.setText("**********");
            NvContraPsicol.setForeground(Color.gray);

        }
        if (String.valueOf(CfContraPsicol.getPassword()).isEmpty()) {
            CfContraPsicol.setText("**********");
            CfContraPsicol.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_TxtCeduPsicolMousePressed

    private void TxtDireccPsicolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtDireccPsicolMousePressed
        if (TxtDireccPsicol.getText().equals("Ingrese su Dirección")) {
            TxtDireccPsicol.setText("");
            TxtDireccPsicol.setForeground(Color.black);
        }

        if (TxtNomPsicol.getText().isEmpty()) {
            TxtNomPsicol.setText("Ingrese sus Nombres");
            TxtNomPsicol.setForeground(Color.gray);
        }

        if (TxtApelliPsicol.getText().isEmpty()) {
            TxtApelliPsicol.setText("Ingrese sus Apellidos");
            TxtApelliPsicol.setForeground(Color.gray);
        }
        if (TxtTelefono.getText().isEmpty()) {
            TxtTelefono.setText("Ingrese su Telefono");
            TxtTelefono.setForeground(Color.gray);
        }
        if (TxtCeduPsicol.getText().isEmpty()) {
            TxtCeduPsicol.setText("Ingrese su cedula");
            TxtCeduPsicol.setForeground(Color.gray);
            
        }
        if (TxtCorreoPsicologo.getText().isEmpty()) {
            TxtCorreoPsicologo.setText("Ingrese su Correo");
            TxtCorreoPsicologo.setForeground(Color.gray);
        } 
        if (String.valueOf(NvContraPsicol.getPassword()).isEmpty()) {
            NvContraPsicol.setText("**********");
            NvContraPsicol.setForeground(Color.gray);

        }
        if (String.valueOf(CfContraPsicol.getPassword()).isEmpty()) {
            CfContraPsicol.setText("**********");
            CfContraPsicol.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_TxtDireccPsicolMousePressed

    private void NvContraPsicolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NvContraPsicolMousePressed
        if (String.valueOf(NvContraPsicol.getPassword()).equals("**********")) {
            NvContraPsicol.setText("");
            NvContraPsicol.setForeground(Color.black);
        }
       if (TxtNomPsicol.getText().isEmpty()) {
            TxtNomPsicol.setText("Ingrese sus Nombres");
            TxtNomPsicol.setForeground(Color.gray);
        }

        if (TxtApelliPsicol.getText().isEmpty()) {
            TxtApelliPsicol.setText("Ingrese sus Apellidos");
            TxtApelliPsicol.setForeground(Color.gray);
        }
        if (TxtTelefono.getText().isEmpty()) {
            TxtTelefono.setText("Ingrese su Telefono");
            TxtTelefono.setForeground(Color.gray);
        }
        if (TxtCeduPsicol.getText().isEmpty()) {
            TxtCeduPsicol.setText("Ingrese su cedula");
            TxtCeduPsicol.setForeground(Color.gray);
        }
        if (TxtDireccPsicol.getText().isEmpty()) {
            TxtDireccPsicol.setText("Ingrese su Dirección");
            TxtDireccPsicol.setForeground(Color.gray);
        }
        
        
        if (TxtCorreoPsicologo.getText().isEmpty()) {
            TxtCorreoPsicologo.setText("Ingrese su Correo");
            TxtCorreoPsicologo.setForeground(Color.gray);
        }  
        
        if (String.valueOf(CfContraPsicol.getPassword()).isEmpty()) {
            CfContraPsicol.setText("**********");
            CfContraPsicol.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_NvContraPsicolMousePressed

    private void CfContraPsicolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CfContraPsicolMousePressed
       if (String.valueOf(CfContraPsicol.getPassword()).equals("**********")) {
            CfContraPsicol.setText("");
            CfContraPsicol.setForeground(Color.black);
        }
       if (TxtNomPsicol.getText().isEmpty()) {
            TxtNomPsicol.setText("Ingrese sus Nombres");
            TxtNomPsicol.setForeground(Color.gray);
        }

        if (TxtApelliPsicol.getText().isEmpty()) {
            TxtApelliPsicol.setText("Ingrese sus Apellidos");
            TxtApelliPsicol.setForeground(Color.gray);
        }
        if (TxtTelefono.getText().isEmpty()) {
            TxtTelefono.setText("Ingrese su Telefono");
            TxtTelefono.setForeground(Color.gray);
        }
        if (TxtCeduPsicol.getText().isEmpty()) {
            TxtCeduPsicol.setText("Ingrese su cedula");
            TxtCeduPsicol.setForeground(Color.gray);
        }
        if (TxtDireccPsicol.getText().isEmpty()) {
            TxtDireccPsicol.setText("Ingrese su Dirección");
            TxtDireccPsicol.setForeground(Color.gray);
        }
        
        
        if (TxtCorreoPsicologo.getText().isEmpty()) {
            TxtCorreoPsicologo.setText("Ingrese su Correo");
            TxtCorreoPsicologo.setForeground(Color.gray);
        }  
        
        if (String.valueOf(NvContraPsicol.getPassword()).isEmpty()) {
            NvContraPsicol.setText("**********");
            NvContraPsicol.setForeground(Color.gray);
        }
    }//GEN-LAST:event_CfContraPsicolMousePressed

    private void cbx_discapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_discapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_discapacidadActionPerformed

    private void TxtCorreoPsicologoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtCorreoPsicologoMousePressed
        if (TxtCorreoPsicologo.getText().equals("Ingrese su Correo")) {
            TxtCorreoPsicologo.setText("");
            TxtCorreoPsicologo.setForeground(Color.black);
        }
        if (TxtNomPsicol.getText().isEmpty()) {
            TxtNomPsicol.setText("Ingrese sus Nombres");
            TxtNomPsicol.setForeground(Color.gray);
        }
        if (TxtApelliPsicol.getText().isEmpty()) {
            TxtApelliPsicol.setText("Ingrese sus Apellidos");
            TxtApelliPsicol.setForeground(Color.gray);
        }
        if (TxtTelefono.getText().isEmpty()) {
            TxtTelefono.setText("Ingrese su Telefono");
            TxtTelefono.setForeground(Color.gray);
        }
        if (TxtCeduPsicol.getText().isEmpty()) {
            TxtCeduPsicol.setText("Ingrese su cedula");
            TxtCeduPsicol.setForeground(Color.gray);
        }
        if (TxtDireccPsicol.getText().isEmpty()) {
            TxtDireccPsicol.setText("Ingrese su Dirección");
            TxtDireccPsicol.setForeground(Color.gray);
        }
        
        if (String.valueOf(NvContraPsicol.getPassword()).isEmpty()) {
            NvContraPsicol.setText("**********");
            NvContraPsicol.setForeground(Color.gray);

        }
        if (String.valueOf(CfContraPsicol.getPassword()).isEmpty()) {
            CfContraPsicol.setText("**********");
            CfContraPsicol.setForeground(Color.gray);
        }
    }//GEN-LAST:event_TxtCorreoPsicologoMousePressed

    private void TxtCorreoPsicologoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCorreoPsicologoActionPerformed
        
    }//GEN-LAST:event_TxtCorreoPsicologoActionPerformed

    private void BtnRegistrarsePsicolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarsePsicolActionPerformed

        Persona Mipersona = new Persona();

        Mipersona.setCedula(TxtCeduPsicol.getText());

        Mipersona.setNombre(TxtNomPsicol.getText());
        Mipersona.setApellido(TxtApelliPsicol.getText());
        Mipersona.setDireccion(TxtDireccPsicol.getText());
        Mipersona.setFecha_Nacimiento(calcular_nacimineto());
        String sex;
        if (Femenino.isSelected()) {
            sex = "F";
        } else {
            sex = "M";
        }

        Mipersona.setSexo(sex.charAt(0));
        String codNacional = Asignar_cod_Nacionalidad(Base, CmbBxNacionalidad3Psicol.getSelectedItem().toString());

        Mipersona.setCod_Nacionalidad(codNacional);

        Mipersona.setTelefono(TxtTelefono.getText());
        String discapa=Asignar_cod_dDiscapacidad(Base,cbx_discapacidad.getSelectedItem().toString() );
                
        Mipersona.setCod_Discapacidad(discapa);
        Mipersona.setEmail(TxtCorreoPsicologo.getText());

        if (String.valueOf(NvContraPsicol.getPassword()).equals(String.valueOf(CfContraPsicol.getPassword()))) {
            Mipersona.setContraseña(String.valueOf(NvContraPsicol.getPassword()));
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden");
            NvContraPsicol.requestFocus();
        }
        Base.store(Mipersona);
//////////////////////////////////////////////////////////////////////////////////////////////////////////
        Psicologo elpsic = new Psicologo();
        elpsic.setCod_Psicologo(Calcular_cod_Psicologo(Base));
        elpsic.setFK_Cedula(TxtCeduPsicol.getText());
        
        String especialid=Asignar_cod_Especialidad(Base,TxtEspecializacionPsicol1.getSelectedItem().toString() );
        elpsic.setFK_Cod_Especialidad(especialid);
        elpsic.setAños_Experiencia((int) sp_años.getValue());
        Base.store(elpsic);

        Base.close();

        InicioPsicologo login = new InicioPsicologo();
        login.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_BtnRegistrarsePsicolActionPerformed

    private void TxtCeduPsicolFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtCeduPsicolFocusLost

    }//GEN-LAST:event_TxtCeduPsicolFocusLost

    public String Asignar_cod_Nacionalidad(ObjectContainer Base, String Nacional) {
        Query query = Base.query();
        query.constrain(Nacionalidad.class);

        ObjectSet result = query.execute();

        while (result.hasNext()) {
            Nacionalidad nacionalidad = (Nacionalidad) result.next();
            if (nacionalidad.getNacionalidad().equals(Nacional)) {  // Asume que tienes un método getId() en tu clase Nacionalidad
                return nacionalidad.getCod_Nacionalidad();  // Asume que tienes un método getNombre() en tu clase Nacionalidad
            }
        }
        return null;
    }
    public String Asignar_cod_dDiscapacidad(ObjectContainer Base, String discapac) {
        Query query = Base.query();
        query.constrain(Discapacidad.class);

        ObjectSet result = query.execute();

        while (result.hasNext()) {
            Discapacidad disca= (Discapacidad) result.next();
            if (disca.getTipo_Discapacidad().equals(discapac)) {  // Asume que tienes un método getId() en tu clase Nacionalidad
                return disca.getCod_Discapacidad();  // Asume que tienes un método getNombre() en tu clase Nacionalidad
            }
        }
        return null;
    }
    public String Asignar_cod_Especialidad(ObjectContainer Base, String espe) {
        Query query = Base.query();
        query.constrain(Especializacion.class);

        ObjectSet result = query.execute();

        while (result.hasNext()) {
            Especializacion especial = (Especializacion) result.next();
            if (especial.getEspecializacion().equals(espe)) {  // Asume que tienes un método getId() en tu clase Nacionalidad
                return especial.getCod_Especializacion();  // Asume que tienes un método getNombre() en tu clase Nacionalidad
            }
        }
        return null;
    }


    private void TxtEspecializacionPsicol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEspecializacionPsicol1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEspecializacionPsicol1ActionPerformed
    public void Nacionalidades_ingr(ObjectContainer Base) {
        Query query = Base.query();
        query.constrain(Nacionalidad.class);
        ObjectSet result = query.execute();

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

        while (result.hasNext()) {
            Nacionalidad nacionalidad = (Nacionalidad) result.next();
            String nombre = nacionalidad.getNacionalidad(); // Asume que tienes un método getNombre() en tu clase Nacionalidad
            model.addElement(nombre); // Agrega el nombre al modelo
        }

        CmbBxNacionalidad3Psicol.setModel(model);

    }
    
    public void Discapacidad_ingr(ObjectContainer Base) {
        Query query = Base.query();
        query.constrain(Discapacidad.class);
        ObjectSet result = query.execute();

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

        while (result.hasNext()) {
            Discapacidad  disca= (Discapacidad) result.next();
            String nombre = disca.getTipo_Discapacidad(); // Asume que tienes un método getNombre() en tu clase Nacionalidad
            model.addElement(nombre); // Agrega el nombre al modelo
        }

        cbx_discapacidad.setModel(model);

    }
     public void Especializacion_ingr(ObjectContainer Base) {
        Query query = Base.query();
        query.constrain(Especializacion.class);
        ObjectSet result = query.execute();

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

        while (result.hasNext()) {
            Especializacion  disca= (Especializacion) result.next();
            String nombre = disca.getEspecializacion(); // Asume que tienes un método getNombre() en tu clase Nacionalidad
            model.addElement(nombre); // Agrega el nombre al modelo
        }

        TxtEspecializacionPsicol1.setModel(model);

    }
     

    private void CmbBxNacionalidad3PsicolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CmbBxNacionalidad3PsicolMousePressed


    }//GEN-LAST:event_CmbBxNacionalidad3PsicolMousePressed

    public Date calcular_nacimineto() {
        DateFechaNaciPsicol.setDate(Nacimiento);

        return Nacimiento;
    }

    public static int Verificar_cedula_Persona(ObjectContainer Base, String cedula) {
        Persona elprson = new Persona();
        elprson.setCedula(cedula);
        ObjectSet result = Base.get(elprson);

        return result.size();
    }

    public static int Verificar_codPsicologo(ObjectContainer Base, String cedula) {

        Psicologo elps = new Psicologo();
        elps.setFK_Cedula(cedula);
        ObjectSet result = Base.get(elps);

        return result.size();
    }

    public static String Calcular_cod_Psicologo(ObjectContainer Base) {

        boolean rest = true;
        int aumento = 0;
        String cod;
        do {

            aumento++;

            cod = String.format("P%04d", aumento);

            if (Verificar_codPsicologo(Base, cod) == 0) {
                rest = false;
            }

        } while (rest);

        return cod;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellidos;
    private javax.swing.ButtonGroup BtnGpDiscaPsicol;
    private javax.swing.ButtonGroup BtnGrpSexoPsicol;
    private javax.swing.JButton BtnRegistrarsePsicol;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JLabel Cedula;
    private javax.swing.JPasswordField CfContraPsicol;
    private javax.swing.JComboBox<String> CmbBxNacionalidad3Psicol;
    private javax.swing.JLabel ConfirmarContraseña;
    private com.toedter.calendar.JDateChooser DateFechaNaciPsicol;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel Discapacidad;
    private javax.swing.JLabel Especializacion;
    private javax.swing.JLabel Especializacion1;
    private javax.swing.JLabel Especializacion2;
    private javax.swing.JLabel Especializacion3;
    private javax.swing.JLabel FechaNacimiento;
    private javax.swing.JRadioButton Femenino;
    private javax.swing.JLabel Fondo1;
    private javax.swing.JLabel Nacionalidad_lbl;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel NuevaContraseña;
    private javax.swing.JPasswordField NvContraPsicol;
    private javax.swing.JLabel Psicologo;
    private javax.swing.JLabel Registrarse;
    private javax.swing.JLabel Sexo;
    private javax.swing.JTextField TxtApelliPsicol;
    private javax.swing.JTextField TxtCeduPsicol;
    private javax.swing.JTextField TxtCorreoPsicologo;
    private javax.swing.JTextField TxtDireccPsicol;
    private javax.swing.JComboBox<String> TxtEspecializacionPsicol1;
    private javax.swing.JTextField TxtNomPsicol;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JComboBox<String> cbx_discapacidad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JSpinner sp_años;
    // End of variables declaration//GEN-END:variables
}
